FROM {{ base_image | default("debian:buster-slim") }}


{% if labels -%}
LABEL {% for key, value in labels.items() -%} 
{{ key }}={{ value | quote }} {% endfor %}
{% else %}
LABEL maintainer="github.com/tieonlinux"
{% endif %}
{% if env -%}
ENV {% for key, value in env.items() -%}
{{ key }}={{value | quote }} {% endfor %}
{% endif %}

COPY {% for file in raw_files %}{{ file | quote }} {% endfor %}  /

RUN /bin/sh -x /0.setup_system.sh

RUN /bin/sh -x /1.setup_tshock.sh

VOLUME ["/world", "/config", "/logs", "/plugins"]

WORKDIR /tshock

EXPOSE {{ terraria_port | default(7777)}}

ENTRYPOINT {{ entrypoint | default('["/usr/bin/dumb-init", "--", "/start.py"]') }}
