FROM {{ base_image | default("debian:bullseye-slim") }}


{% if labels -%}
LABEL {% for key, value in labels.items() -%} 
{{ key }}={{ value | quote }} {% endfor %}
{% else %}
LABEL maintainer="github.com/tieonlinux"
{% endif %}
{% if env -%}
ENV {% for key, value in env.items() -%}
{{ key }}={{value | quote }} {% endfor %}
{% endif %}

{% if files -%}
COPY {% for file in files %}{{ file | quote }} {% endfor %}  /
{% endif %}

RUN /bin/sh -x /setup_tshock.sh
USER terraria

VOLUME ["/world", "/config", "/logs", "/plugins"]

WORKDIR /tshock

EXPOSE {{ terraria_port | default(7777)}}

ENTRYPOINT {{ entrypoint | default('["/usr/bin/tini", "--", "/start.sh"]') }}
